/*
 * Copyright (C) 2010 DiamondCore <http://easy-emu.de/>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

#ifndef _OBJECT_FIELDS_H_
#define _OBJECT_FIELDS_H_

// Auto generated for 3.3.5.12213

enum eObjectFields
{
    OBJECT_FIELD_GUID                                                = 0x0,
    OBJECT_FIELD_TYPE                                                = 0x2,
    OBJECT_FIELD_ENTRY                                               = 0x3,
    OBJECT_FIELD_SCALE_X                                             = 0x4,
    OBJECT_FIELD_PADDING                                             = 0x5,
    OBJECT_END                                                       = 0x6
};
enum eUnitFields
{
    UNIT_FIELD_CHARM                                                 = OBJECT_END + 0x00,
    UNIT_FIELD_SUMMON                                                = OBJECT_END + 0x02,
    UNIT_FIELD_CRITTER                                               = OBJECT_END + 0x04,
    UNIT_FIELD_CHARMEDBY                                             = OBJECT_END + 0x06,
    UNIT_FIELD_SUMMONEDBY                                            = OBJECT_END + 0x08,
    UNIT_FIELD_CREATEDBY                                             = OBJECT_END + 0x0A,
    UNIT_FIELD_TARGET                                                = OBJECT_END + 0x0C,
    UNIT_FIELD_CHANNEL_OBJECT                                        = OBJECT_END + 0x0E,
    UNIT_CHANNEL_SPELL                                               = OBJECT_END + 0x10,
    UNIT_FIELD_BYTES_0                                               = OBJECT_END + 0x11,
    UNIT_FIELD_HEALTH                                                = OBJECT_END + 0x12,
    UNIT_FIELD_POWER1                                                = OBJECT_END + 0x13,
    UNIT_FIELD_POWER2                                                = OBJECT_END + 0x14,
    UNIT_FIELD_POWER3                                                = OBJECT_END + 0x15,
    UNIT_FIELD_POWER4                                                = OBJECT_END + 0x16,
    UNIT_FIELD_POWER5                                                = OBJECT_END + 0x17,
    UNIT_FIELD_POWER6                                                = OBJECT_END + 0x18,
    UNIT_FIELD_POWER7                                                = OBJECT_END + 0x19,
    UNIT_FIELD_MAXHEALTH                                             = OBJECT_END + 0x1A,
    UNIT_FIELD_MAXPOWER1                                             = OBJECT_END + 0x1B,
    UNIT_FIELD_MAXPOWER2                                             = OBJECT_END + 0x1C,
    UNIT_FIELD_MAXPOWER3                                             = OBJECT_END + 0x1D,
    UNIT_FIELD_MAXPOWER4                                             = OBJECT_END + 0x1E,
    UNIT_FIELD_MAXPOWER5                                             = OBJECT_END + 0x1F,
    UNIT_FIELD_MAXPOWER6                                             = OBJECT_END + 0x20,
    UNIT_FIELD_MAXPOWER7                                             = OBJECT_END + 0x21,
    UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER                             = OBJECT_END + 0x22,
    UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER                 = OBJECT_END + 0x29,
    UNIT_FIELD_LEVEL                                                 = OBJECT_END + 0x30,
    UNIT_FIELD_FACTIONTEMPLATE                                       = OBJECT_END + 0x31,
    UNIT_VIRTUAL_ITEM_SLOT_ID                                        = OBJECT_END + 0x32,
    UNIT_FIELD_FLAGS                                                 = OBJECT_END + 0x35,
    UNIT_FIELD_FLAGS_2                                               = OBJECT_END + 0x36,
    UNIT_FIELD_AURASTATE                                             = OBJECT_END + 0x37,
    UNIT_FIELD_BASEATTACKTIME                                        = OBJECT_END + 0x38,
    UNIT_FIELD_RANGEDATTACKTIME                                      = OBJECT_END + 0x3A,
    UNIT_FIELD_BOUNDINGRADIUS                                        = OBJECT_END + 0x3B,
    UNIT_FIELD_COMBATREACH                                           = OBJECT_END + 0x3C,
    UNIT_FIELD_DISPLAYID                                             = OBJECT_END + 0x3D,
    UNIT_FIELD_NATIVEDISPLAYID                                       = OBJECT_END + 0x3E,
    UNIT_FIELD_MOUNTDISPLAYID                                        = OBJECT_END + 0x3F,
    UNIT_FIELD_MINDAMAGE                                             = OBJECT_END + 0x40,
    UNIT_FIELD_MAXDAMAGE                                             = OBJECT_END + 0x41,
    UNIT_FIELD_MINOFFHANDDAMAGE                                      = OBJECT_END + 0x42,
    UNIT_FIELD_MAXOFFHANDDAMAGE                                      = OBJECT_END + 0x43,
    UNIT_FIELD_BYTES_1                                               = OBJECT_END + 0x44,
    UNIT_FIELD_PETNUMBER                                             = OBJECT_END + 0x45,
    UNIT_FIELD_PET_NAME_TIMESTAMP                                    = OBJECT_END + 0x46,
    UNIT_FIELD_PETEXPERIENCE                                         = OBJECT_END + 0x47,
    UNIT_FIELD_PETNEXTLEVELEXP                                       = OBJECT_END + 0x48,
    UNIT_DYNAMIC_FLAGS                                               = OBJECT_END + 0x49,
    UNIT_MOD_CAST_SPEED                                              = OBJECT_END + 0x4A,
    UNIT_CREATED_BY_SPELL                                            = OBJECT_END + 0x4B,
    UNIT_NPC_FLAGS                                                   = OBJECT_END + 0x4C,
    UNIT_NPC_EMOTESTATE                                              = OBJECT_END + 0x4D,
    UNIT_FIELD_STAT0                                                 = OBJECT_END + 0x4E,
    UNIT_FIELD_STAT1                                                 = OBJECT_END + 0x4F,
    UNIT_FIELD_STAT2                                                 = OBJECT_END + 0x50,
    UNIT_FIELD_STAT3                                                 = OBJECT_END + 0x51,
    UNIT_FIELD_STAT4                                                 = OBJECT_END + 0x52,
    UNIT_FIELD_POSSTAT0                                              = OBJECT_END + 0x53,
    UNIT_FIELD_POSSTAT1                                              = OBJECT_END + 0x54,
    UNIT_FIELD_POSSTAT2                                              = OBJECT_END + 0x55,
    UNIT_FIELD_POSSTAT3                                              = OBJECT_END + 0x56,
    UNIT_FIELD_POSSTAT4                                              = OBJECT_END + 0x57,
    UNIT_FIELD_NEGSTAT0                                              = OBJECT_END + 0x58,
    UNIT_FIELD_NEGSTAT1                                              = OBJECT_END + 0x59,
    UNIT_FIELD_NEGSTAT2                                              = OBJECT_END + 0x5A,
    UNIT_FIELD_NEGSTAT3                                              = OBJECT_END + 0x5B,
    UNIT_FIELD_NEGSTAT4                                              = OBJECT_END + 0x5C,
    UNIT_FIELD_RESISTANCES                                           = OBJECT_END + 0x5D,
    UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE                            = OBJECT_END + 0x64,
    UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE                            = OBJECT_END + 0x6B,
    UNIT_FIELD_BASE_MANA                                             = OBJECT_END + 0x72,
    UNIT_FIELD_BASE_HEALTH                                           = OBJECT_END + 0x73,
    UNIT_FIELD_BYTES_2                                               = OBJECT_END + 0x74,
    UNIT_FIELD_ATTACK_POWER                                          = OBJECT_END + 0x75,
    UNIT_FIELD_ATTACK_POWER_MODS                                     = OBJECT_END + 0x76,
    UNIT_FIELD_ATTACK_POWER_MULTIPLIER                               = OBJECT_END + 0x77,
    UNIT_FIELD_RANGED_ATTACK_POWER                                   = OBJECT_END + 0x78,
    UNIT_FIELD_RANGED_ATTACK_POWER_MODS                              = OBJECT_END + 0x79,
    UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER                        = OBJECT_END + 0x7A,
    UNIT_FIELD_MINRANGEDDAMAGE                                       = OBJECT_END + 0x7B,
    UNIT_FIELD_MAXRANGEDDAMAGE                                       = OBJECT_END + 0x7C,
    UNIT_FIELD_POWER_COST_MODIFIER                                   = OBJECT_END + 0x7D,
    UNIT_FIELD_POWER_COST_MULTIPLIER                                 = OBJECT_END + 0x84,
    UNIT_FIELD_MAXHEALTHMODIFIER                                     = OBJECT_END + 0x8B,
    UNIT_FIELD_HOVERHEIGHT                                           = OBJECT_END + 0x8C,
    UNIT_FIELD_PADDING                                               = OBJECT_END + 0x8D,
    UNIT_END                                                         = OBJECT_END + 0x8E
};
enum eItemFields
{
    ITEM_FIELD_OWNER                                                 = OBJECT_END + 0x00,
    ITEM_FIELD_CONTAINED                                             = OBJECT_END + 0x02,
    ITEM_FIELD_CREATOR                                               = OBJECT_END + 0x04,
    ITEM_FIELD_GIFTCREATOR                                           = OBJECT_END + 0x06,
    ITEM_FIELD_STACK_COUNT                                           = OBJECT_END + 0x08,
    ITEM_FIELD_DURATION                                              = OBJECT_END + 0x09,
    ITEM_FIELD_SPELL_CHARGES                                         = OBJECT_END + 0x0A,
    ITEM_FIELD_FLAGS                                                 = OBJECT_END + 0x0F,
    ITEM_FIELD_ENCHANTMENT_1_1                                       = OBJECT_END + 0x10,
    ITEM_FIELD_ENCHANTMENT_1_3                                       = OBJECT_END + 0x12,
    ITEM_FIELD_ENCHANTMENT_2_1                                       = OBJECT_END + 0x13,
    ITEM_FIELD_ENCHANTMENT_2_3                                       = OBJECT_END + 0x15,
    ITEM_FIELD_ENCHANTMENT_3_1                                       = OBJECT_END + 0x16,
    ITEM_FIELD_ENCHANTMENT_3_3                                       = OBJECT_END + 0x18,
    ITEM_FIELD_ENCHANTMENT_4_1                                       = OBJECT_END + 0x19,
    ITEM_FIELD_ENCHANTMENT_4_3                                       = OBJECT_END + 0x1B,
    ITEM_FIELD_ENCHANTMENT_5_1                                       = OBJECT_END + 0x1C,
    ITEM_FIELD_ENCHANTMENT_5_3                                       = OBJECT_END + 0x1E,
    ITEM_FIELD_ENCHANTMENT_6_1                                       = OBJECT_END + 0x1F,
    ITEM_FIELD_ENCHANTMENT_6_3                                       = OBJECT_END + 0x21,
    ITEM_FIELD_ENCHANTMENT_7_1                                       = OBJECT_END + 0x22,
    ITEM_FIELD_ENCHANTMENT_7_3                                       = OBJECT_END + 0x24,
    ITEM_FIELD_ENCHANTMENT_8_1                                       = OBJECT_END + 0x25,
    ITEM_FIELD_ENCHANTMENT_8_3                                       = OBJECT_END + 0x27,
    ITEM_FIELD_ENCHANTMENT_9_1                                       = OBJECT_END + 0x28,
    ITEM_FIELD_ENCHANTMENT_9_3                                       = OBJECT_END + 0x2A,
    ITEM_FIELD_ENCHANTMENT_10_1                                      = OBJECT_END + 0x2B,
    ITEM_FIELD_ENCHANTMENT_10_3                                      = OBJECT_END + 0x2D,
    ITEM_FIELD_ENCHANTMENT_11_1                                      = OBJECT_END + 0x2E,
    ITEM_FIELD_ENCHANTMENT_11_3                                      = OBJECT_END + 0x30,
    ITEM_FIELD_ENCHANTMENT_12_1                                      = OBJECT_END + 0x31,
    ITEM_FIELD_ENCHANTMENT_12_3                                      = OBJECT_END + 0x33,
    ITEM_FIELD_PROPERTY_SEED                                         = OBJECT_END + 0x34,
    ITEM_FIELD_RANDOM_PROPERTIES_ID                                  = OBJECT_END + 0x35,
    ITEM_FIELD_DURABILITY                                            = OBJECT_END + 0x36,
    ITEM_FIELD_MAXDURABILITY                                         = OBJECT_END + 0x37,
    ITEM_FIELD_CREATE_PLAYED_TIME                                    = OBJECT_END + 0x38,
    ITEM_FIELD_PAD                                                   = OBJECT_END + 0x39,
    ITEM_END                                                         = OBJECT_END + 0x3A
};
enum ePlayerFields
{
    PLAYER_DUEL_ARBITER                                              = UNIT_END + 0x000,
    PLAYER_FLAGS                                                     = UNIT_END + 0x002,
    PLAYER_GUILDID                                                   = UNIT_END + 0x003,
    PLAYER_GUILDRANK                                                 = UNIT_END + 0x004,
    PLAYER_BYTES                                                     = UNIT_END + 0x005,
    PLAYER_BYTES_2                                                   = UNIT_END + 0x006,
    PLAYER_BYTES_3                                                   = UNIT_END + 0x007,
    PLAYER_DUEL_TEAM                                                 = UNIT_END + 0x008,
    PLAYER_GUILD_TIMESTAMP                                           = UNIT_END + 0x009,
    PLAYER_QUEST_LOG_1_1                                             = UNIT_END + 0x00A,
    PLAYER_QUEST_LOG_1_2                                             = UNIT_END + 0x00B,
    PLAYER_QUEST_LOG_1_3                                             = UNIT_END + 0x00C,
    PLAYER_QUEST_LOG_1_4                                             = UNIT_END + 0x00E,
    PLAYER_QUEST_LOG_2_1                                             = UNIT_END + 0x00F,
    PLAYER_QUEST_LOG_2_2                                             = UNIT_END + 0x010,
    PLAYER_QUEST_LOG_2_3                                             = UNIT_END + 0x011,
    PLAYER_QUEST_LOG_2_5                                             = UNIT_END + 0x013,
    PLAYER_QUEST_LOG_3_1                                             = UNIT_END + 0x014,
    PLAYER_QUEST_LOG_3_2                                             = UNIT_END + 0x015,
    PLAYER_QUEST_LOG_3_3                                             = UNIT_END + 0x016,
    PLAYER_QUEST_LOG_3_5                                             = UNIT_END + 0x018,
    PLAYER_QUEST_LOG_4_1                                             = UNIT_END + 0x019,
    PLAYER_QUEST_LOG_4_2                                             = UNIT_END + 0x01A,
    PLAYER_QUEST_LOG_4_3                                             = UNIT_END + 0x01B,
    PLAYER_QUEST_LOG_4_5                                             = UNIT_END + 0x01D,
    PLAYER_QUEST_LOG_5_1                                             = UNIT_END + 0x01E,
    PLAYER_QUEST_LOG_5_2                                             = UNIT_END + 0x01F,
    PLAYER_QUEST_LOG_5_3                                             = UNIT_END + 0x020,
    PLAYER_QUEST_LOG_5_5                                             = UNIT_END + 0x022,
    PLAYER_QUEST_LOG_6_1                                             = UNIT_END + 0x023,
    PLAYER_QUEST_LOG_6_2                                             = UNIT_END + 0x024,
    PLAYER_QUEST_LOG_6_3                                             = UNIT_END + 0x025,
    PLAYER_QUEST_LOG_6_5                                             = UNIT_END + 0x027,
    PLAYER_QUEST_LOG_7_1                                             = UNIT_END + 0x028,
    PLAYER_QUEST_LOG_7_2                                             = UNIT_END + 0x029,
    PLAYER_QUEST_LOG_7_3                                             = UNIT_END + 0x02A,
    PLAYER_QUEST_LOG_7_5                                             = UNIT_END + 0x02C,
    PLAYER_QUEST_LOG_8_1                                             = UNIT_END + 0x02D,
    PLAYER_QUEST_LOG_8_2                                             = UNIT_END + 0x02E,
    PLAYER_QUEST_LOG_8_3                                             = UNIT_END + 0x02F,
    PLAYER_QUEST_LOG_8_5                                             = UNIT_END + 0x031,
    PLAYER_QUEST_LOG_9_1                                             = UNIT_END + 0x032,
    PLAYER_QUEST_LOG_9_2                                             = UNIT_END + 0x033,
    PLAYER_QUEST_LOG_9_3                                             = UNIT_END + 0x034,
    PLAYER_QUEST_LOG_9_5                                             = UNIT_END + 0x036,
    PLAYER_QUEST_LOG_10_1                                            = UNIT_END + 0x037,
    PLAYER_QUEST_LOG_10_2                                            = UNIT_END + 0x038,
    PLAYER_QUEST_LOG_10_3                                            = UNIT_END + 0x039,
    PLAYER_QUEST_LOG_10_5                                            = UNIT_END + 0x03B,
    PLAYER_QUEST_LOG_11_1                                            = UNIT_END + 0x03C,
    PLAYER_QUEST_LOG_11_2                                            = UNIT_END + 0x03D,
    PLAYER_QUEST_LOG_11_3                                            = UNIT_END + 0x03E,
    PLAYER_QUEST_LOG_11_5                                            = UNIT_END + 0x040,
    PLAYER_QUEST_LOG_12_1                                            = UNIT_END + 0x041,
    PLAYER_QUEST_LOG_12_2                                            = UNIT_END + 0x042,
    PLAYER_QUEST_LOG_12_3                                            = UNIT_END + 0x043,
    PLAYER_QUEST_LOG_12_5                                            = UNIT_END + 0x045,
    PLAYER_QUEST_LOG_13_1                                            = UNIT_END + 0x046,
    PLAYER_QUEST_LOG_13_2                                            = UNIT_END + 0x047,
    PLAYER_QUEST_LOG_13_3                                            = UNIT_END + 0x048,
    PLAYER_QUEST_LOG_13_5                                            = UNIT_END + 0x04A,
    PLAYER_QUEST_LOG_14_1                                            = UNIT_END + 0x04B,
    PLAYER_QUEST_LOG_14_2                                            = UNIT_END + 0x04C,
    PLAYER_QUEST_LOG_14_3                                            = UNIT_END + 0x04D,
    PLAYER_QUEST_LOG_14_5                                            = UNIT_END + 0x04F,
    PLAYER_QUEST_LOG_15_1                                            = UNIT_END + 0x050,
    PLAYER_QUEST_LOG_15_2                                            = UNIT_END + 0x051,
    PLAYER_QUEST_LOG_15_3                                            = UNIT_END + 0x052,
    PLAYER_QUEST_LOG_15_5                                            = UNIT_END + 0x054,
    PLAYER_QUEST_LOG_16_1                                            = UNIT_END + 0x055,
    PLAYER_QUEST_LOG_16_2                                            = UNIT_END + 0x056,
    PLAYER_QUEST_LOG_16_3                                            = UNIT_END + 0x057,
    PLAYER_QUEST_LOG_16_5                                            = UNIT_END + 0x059,
    PLAYER_QUEST_LOG_17_1                                            = UNIT_END + 0x05A,
    PLAYER_QUEST_LOG_17_2                                            = UNIT_END + 0x05B,
    PLAYER_QUEST_LOG_17_3                                            = UNIT_END + 0x05C,
    PLAYER_QUEST_LOG_17_5                                            = UNIT_END + 0x05E,
    PLAYER_QUEST_LOG_18_1                                            = UNIT_END + 0x05F,
    PLAYER_QUEST_LOG_18_2                                            = UNIT_END + 0x060,
    PLAYER_QUEST_LOG_18_3                                            = UNIT_END + 0x061,
    PLAYER_QUEST_LOG_18_5                                            = UNIT_END + 0x063,
    PLAYER_QUEST_LOG_19_1                                            = UNIT_END + 0x064,
    PLAYER_QUEST_LOG_19_2                                            = UNIT_END + 0x065,
    PLAYER_QUEST_LOG_19_3                                            = UNIT_END + 0x066,
    PLAYER_QUEST_LOG_19_5                                            = UNIT_END + 0x068,
    PLAYER_QUEST_LOG_20_1                                            = UNIT_END + 0x069,
    PLAYER_QUEST_LOG_20_2                                            = UNIT_END + 0x06A,
    PLAYER_QUEST_LOG_20_3                                            = UNIT_END + 0x06B,
    PLAYER_QUEST_LOG_20_5                                            = UNIT_END + 0x06D,
    PLAYER_QUEST_LOG_21_1                                            = UNIT_END + 0x06E,
    PLAYER_QUEST_LOG_21_2                                            = UNIT_END + 0x06F,
    PLAYER_QUEST_LOG_21_3                                            = UNIT_END + 0x070,
    PLAYER_QUEST_LOG_21_5                                            = UNIT_END + 0x072,
    PLAYER_QUEST_LOG_22_1                                            = UNIT_END + 0x073,
    PLAYER_QUEST_LOG_22_2                                            = UNIT_END + 0x074,
    PLAYER_QUEST_LOG_22_3                                            = UNIT_END + 0x075,
    PLAYER_QUEST_LOG_22_5                                            = UNIT_END + 0x077,
    PLAYER_QUEST_LOG_23_1                                            = UNIT_END + 0x078,
    PLAYER_QUEST_LOG_23_2                                            = UNIT_END + 0x079,
    PLAYER_QUEST_LOG_23_3                                            = UNIT_END + 0x07A,
    PLAYER_QUEST_LOG_23_5                                            = UNIT_END + 0x07C,
    PLAYER_QUEST_LOG_24_1                                            = UNIT_END + 0x07D,
    PLAYER_QUEST_LOG_24_2                                            = UNIT_END + 0x07E,
    PLAYER_QUEST_LOG_24_3                                            = UNIT_END + 0x07F,
    PLAYER_QUEST_LOG_24_5                                            = UNIT_END + 0x081,
    PLAYER_QUEST_LOG_25_1                                            = UNIT_END + 0x082,
    PLAYER_QUEST_LOG_25_2                                            = UNIT_END + 0x083,
    PLAYER_QUEST_LOG_25_3                                            = UNIT_END + 0x084,
    PLAYER_QUEST_LOG_25_5                                            = UNIT_END + 0x086,
    PLAYER_VISIBLE_ITEM_1_ENTRYID                                    = UNIT_END + 0x087,
    PLAYER_VISIBLE_ITEM_1_ENCHANTMENT                                = UNIT_END + 0x088,
    PLAYER_VISIBLE_ITEM_2_ENTRYID                                    = UNIT_END + 0x089,
    PLAYER_VISIBLE_ITEM_2_ENCHANTMENT                                = UNIT_END + 0x08A,
    PLAYER_VISIBLE_ITEM_3_ENTRYID                                    = UNIT_END + 0x08B,
    PLAYER_VISIBLE_ITEM_3_ENCHANTMENT                                = UNIT_END + 0x08C,
    PLAYER_VISIBLE_ITEM_4_ENTRYID                                    = UNIT_END + 0x08D,
    PLAYER_VISIBLE_ITEM_4_ENCHANTMENT                                = UNIT_END + 0x08E,
    PLAYER_VISIBLE_ITEM_5_ENTRYID                                    = UNIT_END + 0x08F,
    PLAYER_VISIBLE_ITEM_5_ENCHANTMENT                                = UNIT_END + 0x090,
    PLAYER_VISIBLE_ITEM_6_ENTRYID                                    = UNIT_END + 0x091,
    PLAYER_VISIBLE_ITEM_6_ENCHANTMENT                                = UNIT_END + 0x092,
    PLAYER_VISIBLE_ITEM_7_ENTRYID                                    = UNIT_END + 0x093,
    PLAYER_VISIBLE_ITEM_7_ENCHANTMENT                                = UNIT_END + 0x094,
    PLAYER_VISIBLE_ITEM_8_ENTRYID                                    = UNIT_END + 0x095,
    PLAYER_VISIBLE_ITEM_8_ENCHANTMENT                                = UNIT_END + 0x096,
    PLAYER_VISIBLE_ITEM_9_ENTRYID                                    = UNIT_END + 0x097,
    PLAYER_VISIBLE_ITEM_9_ENCHANTMENT                                = UNIT_END + 0x098,
    PLAYER_VISIBLE_ITEM_10_ENTRYID                                   = UNIT_END + 0x099,
    PLAYER_VISIBLE_ITEM_10_ENCHANTMENT                               = UNIT_END + 0x09A,
    PLAYER_VISIBLE_ITEM_11_ENTRYID                                   = UNIT_END + 0x09B,
    PLAYER_VISIBLE_ITEM_11_ENCHANTMENT                               = UNIT_END + 0x09C,
    PLAYER_VISIBLE_ITEM_12_ENTRYID                                   = UNIT_END + 0x09D,
    PLAYER_VISIBLE_ITEM_12_ENCHANTMENT                               = UNIT_END + 0x09E,
    PLAYER_VISIBLE_ITEM_13_ENTRYID                                   = UNIT_END + 0x09F,
    PLAYER_VISIBLE_ITEM_13_ENCHANTMENT                               = UNIT_END + 0x0A0,
    PLAYER_VISIBLE_ITEM_14_ENTRYID                                   = UNIT_END + 0x0A1,
    PLAYER_VISIBLE_ITEM_14_ENCHANTMENT                               = UNIT_END + 0x0A2,
    PLAYER_VISIBLE_ITEM_15_ENTRYID                                   = UNIT_END + 0x0A3,
    PLAYER_VISIBLE_ITEM_15_ENCHANTMENT                               = UNIT_END + 0x0A4,
    PLAYER_VISIBLE_ITEM_16_ENTRYID                                   = UNIT_END + 0x0A5,
    PLAYER_VISIBLE_ITEM_16_ENCHANTMENT                               = UNIT_END + 0x0A6,
    PLAYER_VISIBLE_ITEM_17_ENTRYID                                   = UNIT_END + 0x0A7,
    PLAYER_VISIBLE_ITEM_17_ENCHANTMENT                               = UNIT_END + 0x0A8,
    PLAYER_VISIBLE_ITEM_18_ENTRYID                                   = UNIT_END + 0x0A9,
    PLAYER_VISIBLE_ITEM_18_ENCHANTMENT                               = UNIT_END + 0x0AA,
    PLAYER_VISIBLE_ITEM_19_ENTRYID                                   = UNIT_END + 0x0AB,
    PLAYER_VISIBLE_ITEM_19_ENCHANTMENT                               = UNIT_END + 0x0AC,
    PLAYER_CHOSEN_TITLE                                              = UNIT_END + 0x0AD,
    PLAYER_FAKE_INEBRIATION                                          = UNIT_END + 0x0AE,
    PLAYER_FIELD_PAD_0                                               = UNIT_END + 0x0AF,
    PLAYER_FIELD_INV_SLOT_HEAD                                       = UNIT_END + 0x0B0,
    PLAYER_FIELD_PACK_SLOT_1                                         = UNIT_END + 0x0DE,
    PLAYER_FIELD_BANK_SLOT_1                                         = UNIT_END + 0x0FE,
    PLAYER_FIELD_BANKBAG_SLOT_1                                      = UNIT_END + 0x136,
    PLAYER_FIELD_VENDORBUYBACK_SLOT_1                                = UNIT_END + 0x144,
    PLAYER_FIELD_KEYRING_SLOT_1                                      = UNIT_END + 0x15C,
    PLAYER_FIELD_CURRENCYTOKEN_SLOT_1                                = UNIT_END + 0x19C,
    PLAYER_FARSIGHT                                                  = UNIT_END + 0x1DC,
    PLAYER__FIELD_KNOWN_TITLES                                       = UNIT_END + 0x1DE,
    PLAYER__FIELD_KNOWN_TITLES1                                      = UNIT_END + 0x1E0,
    PLAYER__FIELD_KNOWN_TITLES2                                      = UNIT_END + 0x1E2,
    PLAYER_FIELD_KNOWN_CURRENCIES                                    = UNIT_END + 0x1E4,
    PLAYER_XP                                                        = UNIT_END + 0x1E6,
    PLAYER_NEXT_LEVEL_XP                                             = UNIT_END + 0x1E7,
    PLAYER_SKILL_INFO_1_1                                            = UNIT_END + 0x1E8,
    PLAYER_CHARACTER_POINTS1                                         = UNIT_END + 0x368,
    PLAYER_CHARACTER_POINTS2                                         = UNIT_END + 0x369,
    PLAYER_TRACK_CREATURES                                           = UNIT_END + 0x36A,
    PLAYER_TRACK_RESOURCES                                           = UNIT_END + 0x36B,
    PLAYER_BLOCK_PERCENTAGE                                          = UNIT_END + 0x36C,
    PLAYER_DODGE_PERCENTAGE                                          = UNIT_END + 0x36D,
    PLAYER_PARRY_PERCENTAGE                                          = UNIT_END + 0x36E,
    PLAYER_EXPERTISE                                                 = UNIT_END + 0x36F,
    PLAYER_OFFHAND_EXPERTISE                                         = UNIT_END + 0x370,
    PLAYER_CRIT_PERCENTAGE                                           = UNIT_END + 0x371,
    PLAYER_RANGED_CRIT_PERCENTAGE                                    = UNIT_END + 0x372,
    PLAYER_OFFHAND_CRIT_PERCENTAGE                                   = UNIT_END + 0x373,
    PLAYER_SPELL_CRIT_PERCENTAGE1                                    = UNIT_END + 0x374,
    PLAYER_SHIELD_BLOCK                                              = UNIT_END + 0x37B,
    PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE                              = UNIT_END + 0x37C,
    PLAYER_EXPLORED_ZONES_1                                          = UNIT_END + 0x37D,
    PLAYER_REST_STATE_EXPERIENCE                                     = UNIT_END + 0x3FD,
    PLAYER_FIELD_COINAGE                                             = UNIT_END + 0x3FE,
    PLAYER_FIELD_MOD_DAMAGE_DONE_POS                                 = UNIT_END + 0x3FF,
    PLAYER_FIELD_MOD_DAMAGE_DONE_NEG                                 = UNIT_END + 0x406,
    PLAYER_FIELD_MOD_DAMAGE_DONE_PCT                                 = UNIT_END + 0x40D,
    PLAYER_FIELD_MOD_HEALING_DONE_POS                                = UNIT_END + 0x414,
    PLAYER_FIELD_MOD_HEALING_PCT                                     = UNIT_END + 0x415,
    PLAYER_FIELD_MOD_HEALING_DONE_PCT                                = UNIT_END + 0x416,
    PLAYER_FIELD_MOD_TARGET_RESISTANCE                               = UNIT_END + 0x417,
    PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE                      = UNIT_END + 0x418,
    PLAYER_FIELD_BYTES                                               = UNIT_END + 0x419,
    PLAYER_AMMO_ID                                                   = UNIT_END + 0x41A,
    PLAYER_SELF_RES_SPELL                                            = UNIT_END + 0x41B,
    PLAYER_FIELD_PVP_MEDALS                                          = UNIT_END + 0x41C,
    PLAYER_FIELD_BUYBACK_PRICE_1                                     = UNIT_END + 0x41D,
    PLAYER_FIELD_BUYBACK_TIMESTAMP_1                                 = UNIT_END + 0x429,
    PLAYER_FIELD_KILLS                                               = UNIT_END + 0x435,
    PLAYER_FIELD_TODAY_CONTRIBUTION                                  = UNIT_END + 0x436,
    PLAYER_FIELD_YESTERDAY_CONTRIBUTION                              = UNIT_END + 0x437,
    PLAYER_FIELD_LIFETIME_HONORBALE_KILLS                            = UNIT_END + 0x438,
    PLAYER_FIELD_BYTES2                                              = UNIT_END + 0x439,
    PLAYER_FIELD_WATCHED_FACTION_INDEX                               = UNIT_END + 0x43A,
    PLAYER_FIELD_COMBAT_RATING_1                                     = UNIT_END + 0x43B,
    PLAYER_FIELD_ARENA_TEAM_INFO_1_1                                 = UNIT_END + 0x454,
    PLAYER_FIELD_HONOR_CURRENCY                                      = UNIT_END + 0x469,
    PLAYER_FIELD_ARENA_CURRENCY                                      = UNIT_END + 0x46A,
    PLAYER_FIELD_MAX_LEVEL                                           = UNIT_END + 0x46B,
    PLAYER_FIELD_DAILY_QUESTS_1                                      = UNIT_END + 0x46C,
    PLAYER_RUNE_REGEN_1                                              = UNIT_END + 0x485,
    PLAYER_NO_REAGENT_COST_1                                         = UNIT_END + 0x489,
    PLAYER_FIELD_GLYPH_SLOTS_1                                       = UNIT_END + 0x48C,
    PLAYER_FIELD_GLYPHS_1                                            = UNIT_END + 0x492,
    PLAYER_GLYPHS_ENABLED                                            = UNIT_END + 0x498,
    PLAYER_PET_SPELL_POWER                                           = UNIT_END + 0x499,
    PLAYER_END                                                       = UNIT_END + 0x49A
};
enum eContainerFields
{
    CONTAINER_FIELD_NUM_SLOTS                                        = ITEM_END + 0x00,
    CONTAINER_ALIGN_PAD                                              = ITEM_END + 0x01,
    CONTAINER_FIELD_SLOT_1                                           = ITEM_END + 0x02,
    CONTAINER_END                                                    = ITEM_END + 0x4A
};
enum eGameObjectFields
{
    GAMEOBJECT_CREATED_BY                                            = OBJECT_END + 0x0,
    GAMEOBJECT_DISPLAYID                                             = OBJECT_END + 0x2,
    GAMEOBJECT_FLAGS                                                 = OBJECT_END + 0x3,
    GAMEOBJECT_PARENTROTATION                                        = OBJECT_END + 0x4,
    GAMEOBJECT_DYNAMIC                                               = OBJECT_END + 0x8,
    GAMEOBJECT_FACTION                                               = OBJECT_END + 0x9,
    GAMEOBJECT_LEVEL                                                 = OBJECT_END + 0xA,
    GAMEOBJECT_BYTES_1                                               = OBJECT_END + 0xB,
    GAMEOBJECT_END                                                   = OBJECT_END + 0xC
};
enum eDynamicObjectFields
{
    DYNAMICOBJECT_CASTER                                             = OBJECT_END + 0x0,
    DYNAMICOBJECT_BYTES                                              = OBJECT_END + 0x2,
    DYNAMICOBJECT_SPELLID                                            = OBJECT_END + 0x3,
    DYNAMICOBJECT_RADIUS                                             = OBJECT_END + 0x4,
    DYNAMICOBJECT_CASTTIME                                           = OBJECT_END + 0x5,
    DYNAMICOBJECT_END                                                = OBJECT_END + 0x6
};
enum eCorpseFields
{
    CORPSE_FIELD_OWNER                                               = OBJECT_END + 0x00,
    CORPSE_FIELD_PARTY                                               = OBJECT_END + 0x02,
    CORPSE_FIELD_DISPLAY_ID                                          = OBJECT_END + 0x04,
    CORPSE_FIELD_ITEM                                                = OBJECT_END + 0x05,
    CORPSE_FIELD_BYTES_1                                             = OBJECT_END + 0x18,
    CORPSE_FIELD_BYTES_2                                             = OBJECT_END + 0x19,
    CORPSE_FIELD_GUILD                                               = OBJECT_END + 0x1A,
    CORPSE_FIELD_FLAGS                                               = OBJECT_END + 0x1B,
    CORPSE_FIELD_DYNAMIC_FLAGS                                       = OBJECT_END + 0x1C,
    CORPSE_FIELD_PAD                                                 = OBJECT_END + 0x1D,
    CORPSE_END                                                       = OBJECT_END + 0x1E
};
#endif
