#!/bin/bash
# Massive Network Game Object Server
# autorestart Script

while :
do
	echo "WorldServer restarted"
	echo `date` >> crash.log &
	./WorldServer | tail -n 20 >> crash.log
	echo " " >> crash.log &
	pid=`ps ax | awk '($5 ~ /WorldServer/) { print $1 }'`
	wait $pid
        echo `date` ", WorldServer crashed and restarted." >> serverlog
done
